### PR TITLE
Created translations for nl_BE and nl_NL

### PR DESCRIPTION
**Pull request by Jefwillems**

### CODE REVIEW

**Comment by notjuliee** [comment]
Looks good to me, thanks!

**Comment by Jefwillems** [comment]
I would translate more if i were able to speak more languages, but this should do for now.

**Comment by notjuliee** [comment]
Well, thank you very much for your contribution.

I'm gonna be adding more strings soon, would you be able to do those too?

**Comment by Jefwillems** [comment]
yes, shouldn't be a problem

**Comment by notjuliee** [comment]
Awesome, thank you very much!

I added you to [CREDITS.md](https://github.com/joonatoona/OpenMineMods/blob/master/CREDITS.md), is that OK?

**Comment by Jefwillems** [comment]
Awesome!

**Comment by notjuliee** [comment]
Cool, all the strings for v1.1 are now in `Strings.py`, if you want to translate those before I release that would be awesome!

**Comment by Jefwillems** [comment]
Alright,
I'll get working on it right away.

**Pull request merged**
